#pandas专门为处理表格和混杂数据设计的，而Numpy更适合处理统一的数值数组数据

#paddas数据结构
##两个主要数据结构：Series和DataFrame

In [18]:
import pandas as pd
import numpy as np

In [3]:
from pandas import Series,DataFrame

Series是一种类似于以为数组的对象，由一组数据（各种Numpy数据类型）和与之相关的数据标签（索引）组成

In [4]:
obj = Series([4,7,-5,3])

In [5]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [8]:
obj2 = Series([4,7,-5,9],index=['a','b','c','d'])

In [9]:
obj2

a    4
b    7
c   -5
d    9
dtype: int64

In [10]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [11]:
obj2['a']

4

In [12]:
obj2['d']=-8

In [13]:
obj2[['c','a','d']]

c   -5
a    4
d   -8
dtype: int64

In [19]:
obj2*2

a     8
b    14
c   -10
d   -16
dtype: int64

In [21]:
np.exp(2)

7.38905609893065

In [22]:
np.exp(obj2)

a      54.598150
b    1096.633158
c       0.006738
d       0.000335
dtype: float64

DataFrame是一个表格型的数据结构，含有有序的列。以二维结构保存数据，但可以轻松表示为更高维度的数据（层次化索引的表格行数据）

建DataFrame，最常用的是直接传入一个由等长列表或numpy数组组成的字典

In [14]:
data = {'state':['a','b','c','d','e','wahaha'],'year':['2000','2001','2002','2003','2004','2005'],'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}

In [15]:
frame = pd.DataFrame(data)

In [16]:
frame

pop   state  year
0  1.5       a  2000
1  1.7       b  2001
2  3.6       c  2002
3  2.4       d  2003
4  2.9       e  2004
5  3.2  wahaha  2005

In [17]:
frame.head()#对于特别大的DataFrame，head方法会选取前5行

pop state  year
0  1.5     a  2000
1  1.7     b  2001
2  3.6     c  2002
3  2.4     d  2003
4  2.9     e  2004

In [24]:
pd.DataFrame(data,columns = ['year','state','pop'])

year   state  pop
0  2000       a  1.5
1  2001       b  1.7
2  2002       c  3.6
3  2003       d  2.4
4  2004       e  2.9
5  2005  wahaha  3.2

In [26]:
frame2 = pd.DataFrame(data,columns = ['year','state','pop','debt'],
            index = ['one','two','three','four','five','six'])
frame2

year   state  pop debt
one    2000       a  1.5  NaN
two    2001       b  1.7  NaN
three  2002       c  3.6  NaN
four   2003       d  2.4  NaN
five   2004       e  2.9  NaN
six    2005  wahaha  3.2  NaN

In [27]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [28]:
frame2.state

one           a
two           b
three         c
four          d
five          e
six      wahaha
Name: state, dtype: object

In [29]:
frame2.loc['three']

year     2002
state       c
pop       3.6
debt      NaN
Name: three, dtype: object

In [30]:
frame2.iloc[2]

year     2002
state       c
pop       3.6
debt      NaN
Name: three, dtype: object

In [31]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000       a  1.5  16.5
two    2001       b  1.7  16.5
three  2002       c  3.6  16.5
four   2003       d  2.4  16.5
five   2004       e  2.9  16.5
six    2005  wahaha  3.2  16.5

In [32]:
frame2.debt = np.arange(6.)
frame2

year   state  pop  debt
one    2000       a  1.5   0.0
two    2001       b  1.7   1.0
three  2002       c  3.6   2.0
four   2003       d  2.4   3.0
five   2004       e  2.9   4.0
six    2005  wahaha  3.2   5.0

In [33]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000       a  1.5   NaN
two    2001       b  1.7  -1.2
three  2002       c  3.6   NaN
four   2003       d  2.4  -1.5
five   2004       e  2.9  -1.7
six    2005  wahaha  3.2   NaN

In [35]:
frame2['eastern'] = frame2.state =='a'
frame2

year   state  pop  debt  eastern
one    2000       a  1.5   NaN     True
two    2001       b  1.7  -1.2    False
three  2002       c  3.6   NaN    False
four   2003       d  2.4  -1.5    False
five   2004       e  2.9  -1.7    False
six    2005  wahaha  3.2   NaN    False

In [36]:
del frame2['eastern']

In [37]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [38]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [39]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [40]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [41]:
pdata = {'Ohio': frame3['Ohio'][:-1],
'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [42]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [43]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [44]:
frame2.values

array([['2000', 'a', 1.5, nan],
       ['2001', 'b', 1.7, -1.2],
       ['2002', 'c', 3.6, nan],
       ['2003', 'd', 2.4, -1.5],
       ['2004', 'e', 2.9, -1.7],
       ['2005', 'wahaha', 3.2, nan]], dtype=object)

In [45]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [46]:
index[1:]

Index(['b', 'c'], dtype='object')

In [48]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [49]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [50]:
obj2.index is labels

True

In [51]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [52]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [53]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [54]:

obj3.reindex(range(6),method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [55]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index=['a', 'c', 'd'],
                     columns = ['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [56]:

frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [57]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [58]:

states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

丢弃某条轴上的一个或多个项很简单，只要有一个索引数组或列表即可。由于需要执行一些数据整理和集合逻辑，所 以drop方法返回的是一个在指定轴上删除了指定值的新对象：

In [59]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [60]:
new_obj=obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [61]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [62]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [63]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [64]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [65]:
obj['b']

1.0

In [66]:

obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [67]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
              index=['Ohio', 'Colorado', 'Utah', 'New York'],
              columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [68]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [69]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [70]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [71]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


对于DataFrame的行的标签索引，我引入了特殊的标签运算符loc和iloc。它们可以让你用类似NumPy的标记，使用 轴标签（loc）或整数索引（iloc），从DataFrame选择行和列的子集。

In [72]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [73]:

ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [75]:

ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [76]:

df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
index=['Ohio', 'Texas', 'Colorado'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [77]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

因为'c'和'e'列均不在两个DataFrame对象中，在结果中以缺省值呈现。行也是同样。 如果DataFrame对象相加，没有共用的列或行标签，结果都会是空

In [78]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [79]:
df1 = pd.DataFrame({'A': [1, 2]})
df1

A
0  1
1  2

In [80]:

df2 = pd.DataFrame({'B': [3, 4]})
df2

B
0  3
1  4

In [81]:

c = df1-df2
c

A   B
0 NaN NaN
1 NaN NaN

In [82]:
c.fillna(1)

A    B
0  1.0  1.0
1  1.0  1.0

In [83]:

arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [84]:
arr[1]

array([4., 5., 6., 7.])

从arr减去arr[0]，每一行都会执行这个操作。这就叫做广播（broadcasting）

In [85]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])